### ISSUE TITLE
how to access oracle manager

### ISSUE THREAD

**Issue by kshitizlondon** [ufoscout/docker-oracle-11g#1]
usually it is like this:
https://localhost:5500/em/

I used this to run the docker container:

docker run --privileged -p 1521:1521 -p 5500:5500 -d some/oracle-11g:latest

I am able to exec into the docker successfully but can't able to access manager using the browser.

Please advice.

**Comment by ufoscout** [comment]
The "-p 5500:5500" option has no effect because the image does not expose that port.
I have never used Oracle Manager so I don't know much about it; however, if it is available by default and the port is the one you said, then the oracle-11g/Dockerfile file has to be modified to expose port 5500. This can be achieved changing line 80 of the script from:

```
EXPOSE 1521 1158
```

to:

```
EXPOSE 1521 1158 5500
```

Instead of creating the image from scratch that takes long time, you could try to create a new docker image that extends from this one and exposes the port you need.
Please let me know whether you succeed with this.

**Comment by phamhonglam90** [comment]
How to import dump file.
I have a folder in windows "C:\dump"


I'm using run command like this:
> docker run --privileged -p 1521:1521 -v C:\dump:\mnt -d --name orcl11g jhouzard/oracle-11g-ee 

Then, I exec into the docker successfully , but in folder \mnt have nothing.
Please advice.

**Comment by ufoscout** [comment]
@phamhonglam90 your question is not related to this issue. However, I guess the problem is that you are using "\" instead of "/" in the volume name.
